//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace lmssite.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MENU
    {
        public System.Guid KID { get; set; }
        public string Menu_No { get; set; }
        public string Menu_Name { get; set; }
        public int Menu_Level { get; set; }
        public Nullable<System.Guid> Menu_ParentId { get; set; }
        public string Menu_Remark { get; set; }
        public bool Is_Delete { get; set; }
        public string Crt_Code { get; set; }
        public string Crt_Name { get; set; }
        public System.DateTime Crt_Time { get; set; }
        public string Mdf_Code { get; set; }
        public string Mdf_Name { get; set; }
        public Nullable<System.DateTime> Mdf_Time { get; set; }
        public string Menu_Url { get; set; }
        public string Menu_Icon { get; set; }
        public byte[] VID { get; set; }
    }
}
